<?php if(isset($exceptionsMessages)): ?>
<div class="alert">
    <p class="title">Erreur Fatal</p>
    <div class="simple-alert">
        <p class="alert-message"><?= $exceptionsMessages[0] ?></p> <button class="dismiss-alert">Aceepter</button>
    </div>
    <?php if(getenv("mod") == "debug"): ?> 
        <?php foreach($exceptionsBlock as $exceptions): ?>
            <p> <span> L'erreur a été rencontrée dans le fichier :</span> <?= $exceptions["file"] ?> || Message: <?= $exceptions["message"] ?> || Ligne: <?= $exceptions["line"] ?></p>
            <div class="description">
                <?php foreach($exceptions["traces"] as $exception): ?>
                    <p> Fichier Concerné: <?= $exception["file"] ?> || Fonction liée: <?= $exception["function"] ?> || Ligne: <?= $exception["line"] ?></p>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
    <?php endif;?>
</div>
<?php endif;?>
<?php if(isset($errors)): ?>
<div class="warning">
    <p class="title">Avertissement</p>
    <?php $index2 = 0; foreach($errors as $error): ?>
        <p> Fichier concerné : <?= $error["file"] ?> || Message: <?= $error["message"] ?> || Ligne: <?= $error["line"] ?></p>
    <?php endforeach; ?>
</div>
<?php endif;?>
<?php if(count($GLOBALS["notifications"]) > 0): ?>
    <?php for($i = 0; $i< count($GLOBALS["notifications"]); $i++): ?>
    <!-- ici on boucle sur le tableau de notification et arrivé au premier élément qui représente le type (succès ou échec) -->
    <!-- on ajoute 1 à l'index pour atteindre le message de notification et donc récupérer toute les infos nécessaire pour remplire la div de notification -->
        <div class="<?= $GLOBALS["notifications"][$i]; $i++; ?>">
            <p class="title">Information</p>
            <p> <?= $GLOBALS["notifications"][$i] ?> </p>
        </div>
    <?php endfor;?>
<?php endif;?>
