<section class="block block-1 header-block">
    <div class="block-1-content container">
        <h1>
           Contact
        </h1>
    </div>
</section>
 <!-- start Block 1 section movies  -->
<section class="block-contact">
    <div class="block-contact-content block-form-content  container">
        <h2>Soyez créatifs !</h2>
        <form action="POST">
            <div class="input-block">
                <label for="firstname"> Nom</label>
                <input type="text" name="firstname"></div>
            <div class="input-block">
                <label for="lastname">Prénom</label>
                <input type="text" name="lastname"></div>
            <div class="input-block">
                <label for="email"> E-mail </label>
                <input type="text" name="email"></div>
            <div class="input-block">
                <label for="info">info</label>
                <input type="text" name="info">
            </div> 
            <div class="input-block">
                <label for="message">Message</label>
                <textarea name="message"></textarea>
            </div> 
            <input type="submit" value="envoyer">
        </form>
    </div>
</section>

