<footer>
    <div class="footer-part-1 container">
        <div class="list-footer-1">
            <strong>Company</strong>
            <ul>
                <li><a href="./about">About</a></li>
                <li><a href="./strategy">Strategy</a></li>
            </ul>
        </div>
        <div class="list-footer-2">
            <strong>Policy</strong>
            <ul>
            <li><a href="./privacy-policy">Privacy-policy</a></li>
                <li><a href="">lorem</a></li>
            </ul>
        </div>
        <div class="list-footer-3">
            <strong>Navigation</strong>
            <ul>
            <li><a href="./home">Home</a></li>
            <li><a href="./about">About</a></li>
            <li><a href="./contact">Contact</a></li>
            </ul>
        </div>   
    </div>
    <div class="footer-part-2 container">
        <p>Copyright © 2021. All Rights Reserved By Movifix</p>
    </div>
</footer>