<footer>
    <div class="footer-part-1 container">
        <div class="list-footer-1">
            <strong>Entrprise</strong>
            <ul>
                <li><a href="./about">À propos</a></li>
                <li><a href="./strategy">Stratégie</a></li>
            </ul>
        </div>
        <div class="list-footer-2">
            <strong>Mentions Légales</strong>
            <ul>
                <li>
                    <a href="./privacy-policy">Politique de confidentialité</a>
                </li>
            </ul>
        </div>
        <div class="list-footer-3">
            <strong>Navigation</strong>
            <ul>
            <li><a href="./home">Accueil</a></li>
            <li><a href="./about">À propos</a></li>
            <li><a href="./contact">Contact</a></li>
            </ul>
        </div>   
    </div>
    <div class="footer-part-2 container">
        <p>Copyright © <script> document.write(new Date().getFullYear()) </script>. Tous droits réservés <a href="https://sunitronics.ml">Sunitronics</a> </p>
    </div>
</footer>