 <!-- start Block 1 section movies  -->
 <section class="block block-1">
    <div class="block-1-content container">
        <h1>
            Des films à volonté en un click
        </h1>
        <div>
            <a href="http://" class="button"> regarder maintenant</a>
        </div>
    </div>
</section>

<!-- start Block 2 section movies  -->

<section class="block block-2">
    <div class="block-2-content container">
        <div class="header-block-2">
            <h2>
               À la une
            </h2>
            <ul>
                <li><a href="" class="button"> categorie 1</a></li>
                <li><a href="" class="button"> categorie 1</a></li>
            </ul>
        </div>
        <div class="movies">
            <!-- <div class="movie">                 
                <a href="">
                    <figure>
                        <img src="https://fakeimg.pl/250x300/">
                        <figcaption>
                            10 €
                        </figcaption>
                    </figure>
                </a>
                <div class="movie-info movie-info-top">
                    <p class="movie-title">Aloion</p>
                    <p class="movie-date">2021</p>
                </div>
                <div class="movie-info movie-info-center">
                    <p>info</p>
                    <div>
                        <span>lorem</span>
                        <span>lorem</span>
                    </div>
                </div>
                <div class="movie-info movie-info-bottom">
                    <p><i class="fas fa-cart-plus"></i></p>
                </div>
            </div> -->
            
        </div>
    </div>
</section>
 <!-- end Block 2 section movies  -->
 <section class="block block-3">
     <div class="block-3-content slide container">
        <h2>Vous aimeriez aussi</h2>
        <div class="glide">
            <div class="glide__track" data-glide-el="track">
                <ul class="glide__slides">
                    <li class="glide__slide"><img src="https://fakeimg.pl/300x300/" alt=""></li>
                    <li class="glide__slide"><img src="https://fakeimg.pl/300x300/" alt=""></li>
                    <li class="glide__slide"><img src="https://fakeimg.pl/300x300/" alt=""></li>
                </ul>
            </div>
            <div class="glide__arrows" data-glide-el="controls">
                <button class="glide__arrow glide__arrow--left" data-glide-dir="<">prev</button>
                <button class="glide__arrow glide__arrow--right" data-glide-dir=">">next</button>
            </div>
            <div class="glide__bullets" data-glide-el="controls[nav]">
                <button class="glide__bullet" data-glide-dir="=0"></button>
                <button class="glide__bullet" data-glide-dir="=1"></button>
                <button class="glide__bullet" data-glide-dir="=2"></button>
            </div>
        </div>          
    </div>
 </section>
 <section class="block block-4">
    <div class="block-4-content banner container">
        <div>
            <img src="https://fakeimg.pl/300x500/" alt=""> 
        </div>
        <div>
            <h3>Download Your Shows Watch Offline.</h3>
            <p>
                Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod tempor.There are many variations of passages of lorem Ipsum available, 
                but the majority have suffered alteration in some injected humour.
            </p>
            <p>Lorem ipsum dolor sit amet, consecetur adipiscing elit, sed do eiusmod tempor.</p>
            <p>Lorem ipsum dolor sit amet, consecetur adipiscing elit, sed do eiusmod tempor.</p>
        </div>
    </div>
 </section>