 <!-- start Block 1 section movies  -->
 <section class="block block-1">
    <div class="block-1-content container">
        <h1>
            Movies at will
        </h1>
        <div>
            <a href="http://" class="button"> watch now</a>
        </div>
    </div>
</section>

<!-- start Block 2 section movies  -->

<section class="block block-2">
    <div class="block-2-content container">
        <div class="header-block-2">
            <h2>
                in the spotlight
            </h2>
            <ul>
                <li><a href="" class="button"> categorie 1</a></li>
                <li><a href="" class="button"> categorie 1</a></li>
            </ul>
        </div>
        <div class="movies">
           <!-- React -->
        </div>
    </div>
</section>
 <!-- end Block 2 section movies  -->
 <section class="block block-3">
     <div class="block-3-content slide container">
        <h2>You would also like</h2>
        <div class="glide">
            <!-- React -->
        </div>          
    </div>
 </section>
 <section class="block block-4">
    <div class="block-4-content banner container">
        <!-- React -->
    </div>
 </section>