
         <!-- start Block 1 section movies  -->
         <section class="block-1">
            <div class="block-1-content container">
                <h1>
                    Nos films
                </h1>
            </div>
        </section>

        <!-- start Block 2 section movies  -->

        <!-- Start Film à venir -->
        <section class="block-2">
            <div class="block-2-content container">
                <div class="header-block-2">
                    <h2>
                       Films à venir
                    </h2>
                    <ul>
                        <li><a href=""> categorie 1</a></li>
                        <li><a href=""> categorie 1</a></li>
                    </ul>
                </div>
                <div class="movies">
                    <div class="movie">                 
                        <a href="">
                            <figure>
                                <img src="https://fakeimg.pl/250x300/">
                                <figcaption>
                                    10 €
                                </figcaption>
                            </figure>
                        </a>
                        <div class="movie-info movie-info-top">
                            <p class="movie-title">Aloion</p>
                            <p class="movie-date">2021</p>
                        </div>
                        <div class="movie-info movie-info-center">
                            <p>info</p>
                            <div>
                                <span>lorem</span>
                                <span>lorem</span>
                            </div>
                        </div>
                        <div class="movie-info movie-info-bottom">
                            <p><i class="fas fa-cart-plus"></i></p>
                        </div>
                    </div>
                    <div class="movie">                 
                        <a href="">
                            <figure>
                                <img src="https://fakeimg.pl/250x300/">
                                <figcaption>
                                    10 €
                                </figcaption>
                            </figure>
                        </a>
                        <div class="movie-info movie-info-top">
                            <p class="movie-title">Aloion</p>
                            <p class="movie-date">2021</p>
                        </div>
                        <div class="movie-info movie-info-center">
                            <p>info</p>
                            <div>
                                <span>lorem</span>
                                <span>lorem</span>
                            </div>
                        </div>
                        <div class="movie-info movie-info-bottom">
                            <p><i class="fas fa-cart-plus"></i></p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Film à venir -->
        <section class="block-2">
            <div class="block-2-content container">
                <div class="header-block-2">
                    <h2>
                       À La Une
                    </h2>
                </div>
                <div class="movie">                 
                    <a href="">
                        <figure>
                            <img src="https://fakeimg.pl/250x300/">
                            <figcaption>
                                10 €
                            </figcaption>
                        </figure>
                    </a>
                    <div class="movie-info movie-info-top">
                        <p class="movie-title">Aloion</p>
                        <p class="movie-date">2021</p>
                    </div>
                    <div class="movie-info movie-info-center">
                        <p>info</p>
                        <div>
                            <span>lorem</span>
                            <span>lorem</span>
                        </div>
                    </div>
                    <div class="movie-info movie-info-bottom">
                        <p><i class="fas fa-cart-plus"></i></p>
                    </div>
                </div>
            </div>
        </section>
        