<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">
    <meta name="theme-color" content="#4285f4">
    <link rel="manifest" href="manifest.json">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
    <link rel="apple-touch-icon" href="/public/ressources/icons/apple-touch-icon.png">
    <?php foreach($this->styles as $style): ?>
        <link rel="stylesheet" href="/public/css/<?= $style ?>.css">
    <?php endforeach; ?>
    
    <title><?= $this->view ?></title>
</head>
<body>
    <?php include VIEW_DIR."/header.phtml"; ?>
    <main class="root">
    </main>
    <!-- Start Footer -->
    <?php include VIEW_DIR."/footer.phtml"; ?>
    <!-- End Footer -->
    <script type="module" src="/public/js/bundle.js"></script>
    <?php foreach($this->scripts as $script): ?>
        <!-- <script type="module" src="/public/js/<?= $script ?>.js"></script> -->
    <?php endforeach; ?>

</body>
</html>