<section class="block block-1 header-block">
    <div class="block-1-content container">
        <h1>
           Profil
        </h1>
    </div>
</section>
 <!-- start Block 1 section movies  -->
<section class="block-profil">
    <div class="block-profil-content container">
        <div class="profil-image">
            <?php if($_SESSION['user']['image'] != null): ?>
                <img src="/public/ressources/uploads/<?= $_SESSION['user']['image'] ?>" alt="photo de profile">
            <?php else: ?>
                <img src="https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png" alt="photo de profile">
            <?php endif; ?>
        </div>
        <h2>Un changement d'identité !?</h2>
        <div class="block-form-content container">

            <form method="POST" action="/profile/update" enctype="multipart/form-data">
                <div class="input-block">
                    <label for="firstname"> Nom</label>
                    <input type="text" name="firstname" value="<?= $_SESSION['user']['firstname'] ?>"></div>
                <div class="input-block">
                    <label for="lastname">Prenom</label>
                    <input type="text" name="lastname" value="<?= $_SESSION['user']['lastname'] ?>"></div>
                <div class="input-block">
                    <label for="email"> E-mail </label>
                    <input type="email" name="email" value="<?= $_SESSION['user']['email'] ?>"></div>
                <div class="input-block">
                    <label for="image">Un petit Avatar ?</label>
                    <input type="file" name="image">
                </div> 
                <div class="input-block">
                    <label for="password"> Mot depasse </label>
                    <input type="password" name="password"></div>
                <div class="input-block">
                    <label for="confirm-password">Confirmez votre mots de passe</label>
                    <input type="password" name="confirm-password">
                </div> 
                <input type="submit" value="enregistrer">
            </form>
        </div>
    </div>
</section>

