<section class="block block-1 header-block">
    <div class="block-1-content container">
        <h1>
           Connexion
        </h1>
    </div>
</section>
 <!-- start Block 1 section movies  -->
<section class="block-inscription">
    <div class="block-inscription-content container">
        <div class="inscription-image">
            <img src="/public/ressources/images/eye-sauron-bleu.jpg" alt="">
        </div>
        <h2>Te revoilà ! Tu y a mis du  !</h2>
        <div class="block-form-content container">

            <form method="POST" action="/admin/home">
                
                <div class="input-block">
                    <label for="email"> E-mail </label>
                    <input type="email" name="email"></div>
                <div class="input-block">
                    <label for="password"> Mot depasse </label>
                    <input type="password" name="password"></div>
                <input type="submit" value="connexion">
            </form>
        </div>
    </div>
</section>

